# Generated by Django 6.0.1 on 2026-02-03 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('summary', models.CharField(max_length=200, verbose_name='Resumen')),
                ('end_date', models.DateField(verbose_name='Fecha de finalización')),
                ('demo_url', models.URLField(blank=True, verbose_name='URL de demo')),
                ('repository_url', models.URLField(blank=True, verbose_name='URL del repositorio')),
                ('duration', models.IntegerField(verbose_name='Duración en meses')),
                ('team_members', models.IntegerField(verbose_name='Número de miembros del equipo')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificado')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificado')),
            ],
            options={
                'verbose_name': 'Rol en proyecto',
                'verbose_name_plural': 'Roles en proyectos',
            },
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificado')),
            ],
            options={
                'verbose_name': 'Tipo de proyecto',
                'verbose_name_plural': 'Tipos de proyectos',
            },
        ),
        migrations.CreateModel(
            name='ProjectCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('icon', models.TextField(help_text='SVG del ícono', verbose_name='Ícono')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificado')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='projects.project', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Característica de proyecto',
                'verbose_name_plural': 'Características de proyectos',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/', verbose_name='Imagen')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificado')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.project', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Imagen de proyecto',
                'verbose_name_plural': 'Imágenes de proyectos',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='project_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='projects.projectrole', verbose_name='Rol en proyecto'),
        ),
        migrations.CreateModel(
            name='ProjectTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('icon', models.TextField(help_text='SVG del ícono', verbose_name='Ícono')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificado')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='projects.project', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Tecnología de proyecto',
                'verbose_name_plural': 'Tecnologías de proyectos',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='projects.projecttype', verbose_name='Tipo de proyecto'),
        ),
    ]
