# Generated by Django 6.0.1 on 2026-02-03 18:50

import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(upload_to=projects.models.project_image_path, verbose_name='Imagen'),
        ),
    ]
