# Generated by Django 6.0.1 on 2026-02-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projectimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='short_description',
            field=models.CharField(default='aaa', max_length=300, verbose_name='Descripción corta'),
            preserve_default=False,
        ),
    ]
