# Generated by Django 6.0.1 on 2026-02-04 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_short_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projecttechnology',
            options={'verbose_name': 'Tecnología de proyecto', 'verbose_name_plural': 'Tecnologías de proyectos'},
        ),
        migrations.RemoveField(
            model_name='projecttechnology',
            name='order',
        ),
        migrations.RemoveField(
            model_name='projecttechnology',
            name='project',
        ),
        migrations.CreateModel(
            name='ProjectTechnologyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificado')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technology_links', to='projects.project', verbose_name='Proyecto')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_links', to='projects.projecttechnology', verbose_name='Tecnología')),
            ],
            options={
                'verbose_name': 'Enlace de tecnología de proyecto',
                'verbose_name_plural': 'Enlaces de tecnologías de proyectos',
                'ordering': ['order'],
                'unique_together': {('project', 'technology')},
            },
        ),
    ]
