# Generated by Django 6.0.1 on 2026-03-20 02:25

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcharacteristic',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Descripción'),
        ),
    ]
