# Generated by Django 6.0.1 on 2026-03-20 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_projectcharacteristic_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='short_description',
            field=models.CharField(help_text='Texto que se mostrará en la sección de proyectos en la pantalla principal', max_length=300, verbose_name='Descripción corta'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, help_text='Nombre que se mostrará en la URL', max_length=200, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='project',
            name='summary',
            field=models.CharField(help_text='Texto que se mostrará debajo del título en la visualización del proyecto', max_length=200, verbose_name='Resumen'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(help_text='Título principal', max_length=200, verbose_name='Título'),
        ),
    ]
