# Generated by Django 6.0.1 on 2026-03-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_project_short_description_alter_project_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='og_images/'),
        ),
    ]
