# Generated by Django 6.0.1 on 2026-03-20 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_og_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='og_image',
            field=models.ImageField(blank=True, help_text='De preferencia 1200x630 jpg', null=True, upload_to='og_images/', verbose_name='Imagen Open Graph'),
        ),
    ]
