# Generated by Django 6.0.1 on 2026-03-20 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_project_og_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='og_alt',
            field=models.CharField(default='arremangala arrepujala', help_text='Texto alternativo de la imagen Open Graph', max_length=200, verbose_name='Texto Open Graph'),
            preserve_default=False,
        ),
    ]
