# Generated by Django 6.0.1 on 2026-03-20 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_project_og_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='og_alt',
            field=models.CharField(blank=True, help_text='Texto alternativo de la imagen Open Graph', max_length=200, null=True, verbose_name='Texto Open Graph'),
        ),
    ]
