version: '3.8'

services:
  db:
    image: mysql:8
    container_name: portfolio-db
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - portfolio

  web:
    build: .
    container_name: portfolio-web
    restart: always
    expose:
      - "8000"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - portfolio

  nginx:
    image: nginx:alpine
    container_name: portfolio-nginx
    restart: always
    ports:
      - "8000:80" # Puerto de entrada
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - web
    networks:
      - portfolio

networks:
  portfolio:

volumes:
  mysql_data:
  static_volume:
  media_volume: