# Generated by Django 6.0.1 on 2026-01-23 03:40

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('slug', models.SlugField(unique=True, verbose_name='Nombre en minúsculas y guión bajo')),
                ('base_url', models.CharField(max_length=255, validators=[core.models.validate_base_url], verbose_name='Enlace')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificado')),
            ],
            options={
                'verbose_name': 'Red Social',
                'verbose_name_plural': 'Redes Sociales',
            },
        ),
        migrations.CreateModel(
            name='SocialUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='Nombre de usuario')),
                ('profile_url', models.CharField(max_length=100, verbose_name='Path del perfil')),
                ('text', models.CharField(max_length=100, verbose_name='Texto')),
                ('use', models.CharField(blank=True, max_length=50, null=True, verbose_name='Uso de la red social')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificado')),
                ('social_network', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.socialnetwork', verbose_name='Red Social')),
            ],
            options={
                'verbose_name': 'Usuario de red social',
                'verbose_name_plural': 'Usuarios de redes sociales',
                'ordering': ['order'],
            },
        ),
    ]
