# Generated by Django 6.0.1 on 2026-01-23 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use', models.CharField(max_length=50, unique=True, verbose_name='Uso de la red social')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificado')),
            ],
            options={
                'verbose_name': 'Uso de red social',
                'verbose_name_plural': 'Usos de redes sociales',
            },
        ),
        migrations.AlterField(
            model_name='socialuser',
            name='use',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.socialuse', verbose_name='Uso de la red social'),
        ),
    ]
