# Generated by Django 6.0.1 on 2026-01-23 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialnetwork',
            options={'verbose_name': 'Red Social', 'verbose_name_plural': 'Redes Sociales'},
        ),
        migrations.AlterModelOptions(
            name='socialuser',
            options={'ordering': ['order'], 'verbose_name': 'Usuario de red social', 'verbose_name_plural': 'Usuarios de redes sociales'},
        ),
        migrations.RemoveField(
            model_name='socialnetwork',
            name='icon',
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Nombre en minúsculas y guión bajo'),
        ),
        migrations.AlterField(
            model_name='socialuser',
            name='profile_url',
            field=models.CharField(max_length=100, verbose_name='Path del perfil'),
        ),
    ]
