# Generated by Django 6.0.1 on 2026-01-23 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_socialuse_alter_socialuser_use'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialuser',
            name='use',
        ),
        migrations.DeleteModel(
            name='SocialUse',
        ),
    ]
