# Generated by Django 6.0.1 on 2026-01-23 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_socialuser_use_delete_socialuse'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialuser',
            name='additional_info',
            field=models.CharField(blank=True, max_length=100, verbose_name='Información adicional'),
        ),
    ]
