# Generated by Django 6.0.1 on 2026-01-23 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_socialuser_additional_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialuser',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Orden'),
        ),
    ]
