# Generated by Django 6.0.1 on 2026-01-24 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_socialuser_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialuser',
            name='active',
            field=models.BooleanField(default=True, verbose_name='¿Activo?'),
        ),
        migrations.AddField(
            model_name='socialuser',
            name='is_in_footer',
            field=models.BooleanField(default=False, verbose_name='¿Mostrar en el footer?'),
        ),
    ]
