# Generated by Django 6.0.1 on 2026-01-24 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_socialuser_active_socialuser_is_in_footer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Categoría')),
                ('slug', models.SlugField(unique=True, verbose_name='Nombre en minúsculas y guión bajo')),
                ('active', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificado')),
            ],
            options={
                'verbose_name': 'Categoría de habilidad',
                'verbose_name_plural': 'Categorías de habilidades',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('icon', models.TextField(help_text='SVG del ícono', verbose_name='Ícono')),
                ('active', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificado')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.skillcategory', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Habilidad',
                'verbose_name_plural': 'Habilidades',
                'ordering': ['order'],
            },
        ),
    ]
