# Generated by Django 6.0.1 on 2026-01-24 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_skillcategory_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillcategory',
            name='slug',
        ),
    ]
