# Generated by Django 6.0.1 on 2026-01-24 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_skillcategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skills', to='core.skillcategory', verbose_name='Categoría'),
        ),
    ]
