# Generated by Django 6.0.1 on 2026-01-24 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_skill_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialuser',
            old_name='is_in_footer',
            new_name='is_in_hero',
        ),
    ]
