# Generated by Django 6.0.1 on 2026-01-24 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_is_in_footer_socialuser_is_in_hero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialuser',
            name='is_in_hero',
            field=models.BooleanField(default=False, verbose_name='¿Mostrar en el hero?'),
        ),
    ]
