# Generated by Django 6.0.1 on 2026-03-20 02:25

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_socialuser_is_in_hero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Descripción'),
        ),
    ]
