# Generated by Django 6.0.1 on 2026-03-20 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_skill_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetwork',
            name='slug',
            field=models.SlugField(help_text='Se usará para el link de la red. Debe estar en minúsculas y con guión bajo', unique=True, verbose_name='Slug'),
        ),
    ]
