# Generated by Django 6.0.1 on 2026-03-20 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_socialnetwork_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetwork',
            name='slug',
            field=models.SlugField(help_text='Se usará para el link de la red. Debe estar en minúsculas y con guión bajo.', unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='socialuser',
            name='profile_url',
            field=models.CharField(help_text='Se usará para el link del perfil. Debe estar en minúsculas y con guión bajo.', max_length=100, verbose_name='Path del perfil'),
        ),
    ]
