# Generated by Django 6.0.1 on 2026-03-20 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_socialnetwork_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetwork',
            name='slug',
            field=models.SlugField(help_text='Se usará para el icono de la red social. Debe estar en minúsculas y con guión bajo.', unique=True, verbose_name='Slug'),
        ),
    ]
